name: CI/CD Django + Next.js

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Test & Deploy Django Backend
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
      DJANGO_LOG_LEVEL: "INFO"
      DJANGO_DEBUG_MODULES: "services.strategies.GoogleBookFetcher"

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      # 5. Run Django unit tests
      - name: Run Django unit tests
        working-directory: backend
        run: python manage.py test

      # 6. Deploy to Railway only if tests pass
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: "0d3f7fc1-e0d4-4cb0-a2be-2d92b7faddc9"
          uses: railwayapp/railway-action@v1
